package com.example.myapplication.ui.aboutsoftware;

import androidx.lifecycle.LiveData;
import androidx.lifecycle.MutableLiveData;
import androidx.lifecycle.ViewModel;

public class AboutsoftwareViewModel extends ViewModel {
    private MutableLiveData<String> mText;

    public AboutsoftwareViewModel() {
        mText = new MutableLiveData<>();
        mText.setValue("A total of N159.32bn was generated by States in Q3 2017 while the Q3 2017 YTD revenue generated by\n" +
                "states was put at N491.01bn. This excludes Rivers, Sokoto, Nasarawa, Niger, Kwara, Kano,Katsina, Kebbi,\n" +
                "Gombe, Edo, Born, Bauchi, Adamawa, Abia and Anambra States (represented by -) who have not yet\n" +
                "reported their IGR figures for Q3 2017.\n");
    }

    public LiveData<String> getText() {
        return mText;
    }
}